name: Coverage

on: [push]

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: '6'

      - name: Use Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: Publish coverage
        run: |
          npm ci
          npm run test -- --forceExit --coverage

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true

      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
