name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x]

    steps:
    - uses: actions/checkout@v3
    - uses: supercharge/redis-github-action@1.4.0
      with:
        redis-version: '6'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test -- --forceExit
      env:
        CI: true

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    - uses: supercharge/redis-github-action@1.4.0
      with:
        redis-version: '6'

    - name: Use Node.js 19.x
      uses: actions/setup-node@v1
      with:
        node-version: 19.x

    - name: Publish coverage
      run: |
        npm ci
        npm run test -- --forceExit --coverage

    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel: true

    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
